# -*- coding: utf-8 -*-
"""P110.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ICqjwx0uz4Hwknt9nwjt9qrUSfha8GtH
"""

from google.colab import files 
data=files.upload()

import csv
import pandas as pd 
import plotly.figure_factory as ff 
import plotly.graph_objects as go
import statistics
import random

df = pd.read_csv("data.csv")
data = df["temp"].tolist()
population_mean =statistics.mean(data)
print("Mean of the population is :" , population_mean)

population_stdev = statistics.stdev(data)
print("Standard deveation = " , population_stdev)

def random_set_of_mean(counter) :
        data_set = []
        for i in range(0,counter) :
                random_index = random.randint(0,len(data)-1)
                value = data[random_index]
                data_set.append(value)
        mean = statistics.mean(data_set)
        return mean

def random_set_of_standard_deviation() :
    mean_list = []
    for i in range (0 , 1000) :
        mean = random_set_of_mean(100)
        mean_list.append(mean)
    standard_deviation = statistics.stdev(mean_list)
    print("Standard deviation for thousand samples = " , standard_deviation)


def showFigure (mean_list) :
    fig = ff.create_distplot([mean_list] , ["temp"] , show_hist= False)
    fig.show()

def setup () :
    mean_list = []
    for i in range(0 , 1000) :
            set_of_mean = random_set_of_mean(100)
            mean_list.append(set_of_mean) 

    showFigure(mean_list)


random_set_of_standard_deviation()
setup()